default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: test_ruby

test:
  <<: *default

production:
  <<: *default
  host: postgres://unrdbklufvewwc:b29c19a4eb5c5891f8e370f778545874b6e8db9642df7644318f3ecb23d8b229@ec2-54-227-252-202.compute-1.amazonaws.com:5432/d7p73pg6hgmc16
  password: <%= ENV['ROR_TEST_DATABASE_PASSWORD'] %>
